spring.application.name=myFirstSpringProject
spring.output.ansi.enabled=always
logging.pattern.console=%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %cyan(%thread) %highlight(%-5level) %magenta(%logger{36}) - %gray(%msg%n)